# 실제 워크플로우 등록은 저장소root/.github/workflows에서 해야한다
# 현재 디렉토리의 파일은 워크플로우의 해설본

name: start-workflow-study
on: [push]

jobs:
  A.기본job: 
    runs-on: ubuntu-latest # 깃헙에서 제공하는 해당 OS 서버에서 아래 스탭들이 돌아감
    steps:
      - name: 1. Hello 출력하기
        run: echo "Hello World"
      - name: 2. 여러줄 라인 명령
        run: |
          node -v
          npm -v

  B.병렬Job: # 일반적으로 여러개의 job은 병렬로 돌아간다
    runs-on: macos-latest
    steps:
      - name: 1. software version 출력하기
        run: sw_vers

  C.의존성Job:
    runs-on: windows-latest
    needs: A.기본job # 여기서 의존성이 주입된다.
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      - name: Error Step
        run: doesnotexit