# 실제 워크플로우 등록은 저장소root/.github/workflows에서 해야한다
# 현재 디렉토리의 파일은 워크플로우의 해설본

name: start-workflow-study
on: [push]

jobs:
  A_basic_job: # job 이름은 영문만 가능
    runs-on: ubuntu-latest # 깃헙에서 제공하는 해당 OS 서버에서 아래 스탭들이 돌아감
    steps:
      - name: 1. Hello 출력하기
        run: echo "Hello World"
      - name: 2. 여러줄 라인 명령
        run: |
          node -v
          npm -v

  B_parallel_job: # 일반적으로 여러개의 job은 병렬로 돌아간다
    runs-on: macos-latest
    steps:
      - name: 1. software version 출력하기
        run: sw_vers

  C_dependant_job: # needs항목으로 의존성을 주입할 수 있다.
    runs-on: windows-latest
    needs: A_basic_job
    steps:
      - name: 1. 문자열 출력
        run: Write-Output "Windows String"
      - name: 2. 일부러 에러 출력 # 에러상황을 확인하기 위해 고의로 에러 출력
        run: doesnotexit