name: cmd-log-settings
on: [push]

jobs:
  cmd-log-settings:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
    steps:
      - name: 1. 로그 출력 방식
        run:  |
          echo "::error::This is an error message"
          echo "::debug::This is an debug message"
          echo "::warning::This is a warning message"
          echo "::notice::This is a notice message"

      - name: 2. 로그 그룹으로 보기
        run: |
          echo "::group::My group title"
          echo "Inside group"
          echo "Inside group 2"
          echo "Inside group 3"
          echo "::endgroup::"

      - name: 3. 비밀 정보 마스킹하기
        run: |
          echo "::add-mask::Secret String"
          echo "Secret String"